In [29]:
import pathlib
from pathlib import Path

import pandas as pd
import geopandas as gpd

## Nigeria and togo boundaries

In [53]:
in_path = Path('/home/gajo/DFS/Projects/2021-data-org/4._RESEARCH_n/ML/MLsatellite/data/layers-general/administrative_borders/ne_50m_admin_0_countries/ne_50m_admin_0_countries.shp')
out_folder_path = Path('/home/gajo/DFS/Projects/2021-data-org/4._RESEARCH_n/ML/MLsatellite/Research/WP1_Joaquin/paper-nigeria-cropland/layers')

for country in ['Nigeria', 'Togo']:
    world = gpd.read_file(in_path)
    gdf = world[world['SOVEREIGNT'] ==  country].reset_index(drop=True)
    out_path = out_folder_path / f'{country.lower()}_borders.shp'
    if not out_path.exists():
        gdf.to_file(out_folder_path / f'{country.lower()}_borders.shp')
    else:
        print(out_path, 'already exists!')

## Labels

In [11]:
togo_train_path = Path('../data/processed/togo/data.geojson')
togo_eval_path = Path('../data/processed/togo_evaluation/data.csv')

In [15]:
df_train = gpd.read_file(togo_train_path)
df_train

,is_crop,lat,lon,org_file,index,geometry
0,1,7.633909,1.307211,crop_merged_v2,0,"POLYGON ((1.30702 7.63420, 1.30746 7.63416, 1...."
1,1,7.581720,1.395439,crop_merged_v2,1,"POLYGON ((1.39518 7.58190, 1.39570 7.58188, 1...."
2,1,7.581569,1.402865,crop_merged_v2,2,"POLYGON ((1.40276 7.58175, 1.40308 7.58162, 1...."
3,1,7.590035,1.410863,crop_merged_v2,3,"POLYGON ((1.41080 7.59027, 1.41111 7.59014, 1...."
4,1,7.584598,1.412409,crop_merged_v2,4,"POLYGON ((1.41233 7.58473, 1.41252 7.58468, 1...."
...,...,...,...,...,...,...
1271,0,10.841655,0.027289,noncrop_merged_v2,583,"POLYGON ((0.02698 10.84190, 0.02741 10.84189, ..."
1272,0,10.842342,0.029127,noncrop_merged_v2,584,"POLYGON ((0.02901 10.84254, 0.02924 10.84260, ..."
1273,0,10.844105,0.030248,noncrop_merged_v2,585,"POLYGON ((0.02991 10.84429, 0.03015 10.84442, ..."
1274,0,10.838868,0.029502,noncrop_merged_v2,586,"POLYGON ((0.02921 10.83896, 0.02972 10.83906, ..."
1275,0,10.837921,0.028180,noncrop_merged_v2,587,"POLYGON ((0.02789 10.83826, 0.02858 10.83812, ..."

In [16]:
df_test = pd.read_csv(togo_eval_path)
df_test

     is_crop        lat       lon  index
0          0   9.875907  1.172471      0
1          0   9.180105  1.374695      1
2          0   9.275314  1.196385      2
3          0   7.346575  0.705167      3
4          0   6.777337  0.629817      4
..       ...        ...       ...    ...
301        0   6.575327  1.507141    346
302        1   8.683783  1.129420    347
303        0  10.326000  0.537311    348
304        0   7.832317  0.880575    349
305        1   6.472810  1.502436    350

[306 rows x 4 columns]